-- Entry point. Everything else hangs off lua/config/lazy.lua.
--
-- Layout follows LazyVim's convention so that its own loader picks the files
-- up automatically:
--
--   lua/config/options.lua   loaded after LazyVim's defaults, so it overrides them
--   lua/config/keymaps.lua   same, for keys
--   lua/config/autocmds.lua  same, for autocommands
--   lua/plugins/*.lua        merged into LazyVim's plugin specs
--
-- The ordering is the whole trick: LazyVim sets its defaults first and then
-- sources these, so anything set here wins without having to fight it.
require("config.lazy")
